language: ruby
env:
  matrix:
  - RACK_ENV=development
sudo: false
rvm:
- 2.0.0
services:
- docker
before_install:
- docker pull mumuki/mumuki-minitest-worker
deploy:
  provider: rubygems
  api_key:
    secure: fFyTihkd5s9umz+ujNS022HBb6wSPkXPyJa7cHCIC007haciq36EBeY+Sce6iwGOacDvChks/OrcBtUlPtQzea85PdcmDu3un9lgdIsZd9feP3VGw/9Yzp8uJFP0tZgL0/Izg2qelar6e5iRHS7vb/SAzSa8Cef5ydKeh7XA6sUmwI8mXNr8+xlrqZM7+MOVSVeU3hftE6X6SEg6lGZ9cuf/ndIvK/vkBapTt+crrQmrh0uXIXZtd8+6xKgBlzMOyeo1T1vghS3vjZT2MUYgwjAW6MDW5iOhrfVDgWJQ9Aj0RiedrAl7ap5Sk8UKjRecGslCofd+mBz0KPU7IE08x5Cw3LgtRet6fwyTtXy4lO7EurrSjCbm0UHskpX72GR9X+ueEBgmsX/Q6IYm3bkKfK88R5wZ7S+jspeNN0YLagye1vOZ68l43L/sX/WTKQNNjjWtscgAjRfYcyPBzf7/6D9KYl25G82FfsHB7U55n7WdvQ7LsvfB5O1qx9WIOHgOLNTHT5Z1NzkA1/DOQ8URrx/6ZSdtQSeAtEH4FHaQnvsH5BC1I7XXy4DmdhQcQggkWW1b5Jop9c13Hw+TxHY9F96Zm1CG6YYGTyqVvLiKOF3T7jRJDbVuNKEJbVAnmevUV3A4IKKrBF8rHbFvoPxhSijX8ZJvRUmHQAM8nunF2T8=
  gem: mumuki-minitest-runner
  on:
    tags: true
    repo: mumuki/mumuki-minitest-runner
